### ISSUE TITLE
Create a tag?

### ISSUE THREAD

**Issue by duboism** [mikekatz04/LISAanalysistools#14]
Hello,

We work on project that use this package (namely NataliaKor/lisaflow - currently private).

I have noticed that the `main` branch hasn't moved for some time now (although development branches seem active). Do you think it would be wise to tag a version? This would help when installing packages that depend on this one.

**Comment by mikekatz04** [comment]
Hi, lisatools I going through its release update. So this is now on the main branch.

**Comment by duboism** [comment]
Hi,

Sorry for the delay. I'm not sure I understood your message but from the commits, I understand that you're in the process of merging branches and fixing bugs. So maybe we can expect a stable version soon. Right ?

**Comment by mikekatz04** [comment]
Yes. I would say it is stable now. But there may be a quick flurry of bug activity with a large increase in users.
