### ISSUE TITLE
Query for LISA orbit file

### ISSUE THREAD

**Issue by ChaoZhangCode** [mikekatz04/LISAanalysistools#16]
I have checked the position of spacecraft and used the position to create the normal unit vector towards receiver along links from file.
But the results of normal unit vector don't coincide with the normal unit vector from the files "equalarmlength-orbits.h5".
Maybe I mistake the definition of the normal unit vector.
I would be appreciated that you can upload your file for calculating the orbit in "equalarmlength-orbits.h5".

**Comment by mikekatz04** [comment]
Hello, it is generated with the code LISA Orbits: https://lisa-simulation.pages.in2p3.fr/orbits/latest/.
