### ISSUE TITLE
Potentially missing files on main branch

### ISSUE THREAD

**Issue by SimonMaenaut** [mikekatz04/LISAanalysistools#17]
Dear developers,

As I was trying to install this package from source to explore the option of maybe adding some features, I noticed that some files that are present in the source tarball for lisaanalysistools-1.0.4 on pipy seem to be missing in the main branch of this git repository.

<details>
  <summary>Files included in lisaanalysistools-1.0.4 not present on the main brach</summary>

```
./lisatools/glitch.py
./lisatools/sampling/moves/gbgroupstretch.py
./lisatools/sampling/moves/gbmultipletryrj.py
./lisatools/sampling/moves/gbspecialgroupstretch.py
./lisatools/sampling/moves/gbspecialstretch.py
./lisatools/sampling/moves/mbhspecialmove.py
./lisatools/sampling/moves/placeholder.py
./lisatools/sampling/moves/specialforegroundmove.py
./lisatools/sources
./lisatools/sources/emri
./lisatools/sources/emri/__init__.py
./lisatools/sources/emri/tdiwaveform.py
./lisatools/sources/__init__.py
./lisatools/utils/multigpudataholder.py
./requirements-data.txt
./requirements-demo.txt
./requirements-dev.txt
./requirements-release.txt
./requirements.txt
```
</details>

It's not clear to me which files are necessary, however `pip install -e .` definitely doesn't work without the above directories.

Furthermore, I tried commands in the `Makefile`, however without `tests/testsuites/` I could not check if my install succeeded.

Could you please let me know if I missed a step in the installation, or where I should find the missing files?

Kind regards,
Simon

**Comment by mikekatz04** [comment]
Hello, thank you for pointing this out. Yes, there was a directory that was not added. It should work now.

**Comment by SimonMaenaut** [comment]
Thank you!

It now works on the condition that the environment already has all the required dependencies.
