### ISSUE TITLE
Error when calling `Orbits.configure` with a time array

### ISSUE THREAD

**Issue by acorreia61201** [mikekatz04/LISAanalysistools#20]
I encountered an error when calling `Orbits.configure` with a time array input. Calling the method in this way returns an `UnboundLocalError` that points to an unset flag `make_cpp`. Looking through the source code, it looks like there should be a declaration of `make_cpp` in the elif statement on line 230, although I wasn't sure what the proper behavior should be. It seems based on the surrounding code that `make_cpp` should be set to `True` whenever the orbital time series is being modified, which I'm assuming is the intended behavior if a time array is provided. Should `make_cpp` be set to `True` in this case?

**Comment by mikekatz04** [comment]
Pull request accepted. Thank you!
