### ISSUE TITLE
Error when creating DataResidualArray in GPU

### ISSUE THREAD

**Issue by lcopparoni** [mikekatz04/LISAanalysistools#22]
Hello I incur in the following error when creating a DataResidualArray with a cupy array:
`
  File "/home/lcopparo/miniconda3/envs/emri/lib/python3.12/site-packages/lisaanalysistools-1.0.5-py3.12-linux-x86_64.egg/lisatools/datacontainer.py", line 227, in data_res_arr
    self._data_res_arr = np.asarray(list(new_out), dtype=complex)
`
my conda installation uses the following dependencies:
- cupy-cuda12x       13.2.0
- numpy              1.26.4
- CUDA/12.1

**Comment by mikekatz04** [comment]
There are more GPU capabilities added to the code now. Please let me know if this error persists. I am closing this issue for now.
